using System;
using System.IO;
using System.Text;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif

namespace Unity.Robotics.UrdfImporter
{
    /// <summary>
    /// Copies mesh and texture files that a URDF references from outside the Unity project
    /// into it, so the AssetDatabase can import them.
    ///
    /// URDFs generated by xacro routinely carry absolute `file://` mesh URIs pointing at a
    /// ROS install or a Python site-packages directory. Without staging, the only way to
    /// import such a description is to hand-edit every mesh path.
    /// </summary>
    public static class UrdfAssetStaging
    {
        /// <summary>Folder, relative to the package root, that staged copies land in.</summary>
        public const string StagedFolderName = "ExternalAssets";

        /// <summary>
        /// Copies <paramref name="absoluteSourcePath"/> into the project if it isn't already
        /// there, and returns the project-relative path of the copy. Returns null when the
        /// source doesn't exist or staging isn't possible (at runtime there is no
        /// AssetDatabase, so the original absolute path should be used directly).
        /// </summary>
        public static string StageExternalAsset(string absoluteSourcePath)
        {
#if UNITY_EDITOR
            if (RuntimeUrdf.IsRuntimeMode())
            {
                return null;
            }

            if (string.IsNullOrEmpty(absoluteSourcePath) || !File.Exists(absoluteSourcePath))
            {
                return null;
            }

            string packageRoot = UrdfAssetPathHandler.GetPackageRoot();
            if (string.IsNullOrEmpty(packageRoot))
            {
                return null;
            }

            string relativeDestination = Path.Combine(
                packageRoot,
                StagedFolderName,
                GetSourceFolderKey(absoluteSourcePath),
                Path.GetFileName(absoluteSourcePath)).SetSeparatorChar();

            string absoluteDestination = UrdfAssetPathHandler.GetFullAssetPath(relativeDestination);

            if (NeedsRefresh(absoluteSourcePath, absoluteDestination))
            {
                try
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(absoluteDestination));
                    File.Copy(absoluteSourcePath, absoluteDestination, true);
                    AssetDatabase.ImportAsset(relativeDestination, ImportAssetOptions.ForceSynchronousImport);
                }
                catch (Exception exception)
                {
                    Debug.LogWarning(
                        $"Could not copy external URDF asset '{absoluteSourcePath}' into the project: {exception.Message}");
                    return null;
                }
            }

            return relativeDestination;
#else
            return null;
#endif
        }

        static bool NeedsRefresh(string source, string destination)
        {
            if (!File.Exists(destination))
            {
                return true;
            }

            var sourceInfo = new FileInfo(source);
            var destinationInfo = new FileInfo(destination);
            return sourceInfo.Length != destinationInfo.Length ||
                   sourceInfo.LastWriteTimeUtc > destinationInfo.LastWriteTimeUtc;
        }

        /// <summary>
        /// A stable, readable, collision-free folder name for the source directory. Meshes
        /// from different robots commonly sit in directories that are both called "meshes",
        /// so the directory name alone is not enough to keep them apart.
        /// </summary>
        static string GetSourceFolderKey(string absoluteSourcePath)
        {
            string directory = Path.GetDirectoryName(absoluteSourcePath).SetSeparatorChar();
            string name = Path.GetFileName(directory);
            if (string.IsNullOrEmpty(name))
            {
                name = "root";
            }
            return $"{name}_{ShortHash(directory)}";
        }

        static string ShortHash(string value)
        {
            using (var sha = System.Security.Cryptography.SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(Encoding.UTF8.GetBytes(value));
                var builder = new StringBuilder(8);
                for (int i = 0; i < 4; i++)
                {
                    builder.Append(hash[i].ToString("x2"));
                }
                return builder.ToString();
            }
        }
    }
}
